### ISSUE TITLE
solution branch

### ISSUE THREAD

**Issue by abdhalees** [foundersandcoders/Node-Shell-Workshop#24]
since there isn't a solution branch in this repo, could I and @mrm7moud make one and push our solution to it? @eliascodes?

**Comment by eliasmalik** [comment]
@abdhalees that's a great idea! But I would prefer a solution folder instead of a branch for the reasons in foundersandcoders/master-reference#456 (see [this comment](https://github.com/foundersandcoders/master-reference/issues/456#issuecomment-315138262)).

Since @bradreeder is the maintainer of this repo, let's ask him first. If he's happy with you both doing this, please make a PR and assign @bradreeder to it.

**Comment by bradreeder** [comment]
That sounds like a good addition @abdhalees , thanks a lot for the contribution. ✨ I'd go ahead as @eliascodes has suggested with a solutions folder rather than branch and assign to us both to review when ready. 

There are a few links in this open issue that may be of use to you #11

**Comment by sunuwars** [comment]
@abdhalees , @eliascodes , @bradreeder and @lucymk , this issue seems to have been resolved are you happy for this to be closed?
